import { TemplateResult } from 'lit';
import { YpBaseElement } from '../common/yp-base-element.js';
import '@material/web/dialog/dialog.js';
import '@material/mwc-snackbar';
import '../yp-magic-text/yp-magic-text-dialog.js';
import '../yp-user/yp-login.js';
import '../yp-user/yp-user-edit.js';
import './yp-confirmation-dialog.js';
import '../yp-api-action-dialog/yp-api-action-dialog.js';
import "../yp-user/yp-missing-email.js";
import "../yp-user/yp-registration-questions-dialog.js";
import "../yp-user/yp-forgot-password.js";
import "../yp-user/yp-reset-password.js";
import "../yp-post/yp-post-edit.js";
import "../yp-page/yp-page-dialog.js";
export declare class YpAppDialogs extends YpBaseElement {
    selectedDialog: string | undefined;
    confirmationDialogOpen: boolean;
    pageDialogOpen: boolean;
    magicTextDialogOpen: boolean;
    mediaRecorderOpen: boolean;
    loadingDialogOpen: boolean;
    needsPixelCookieConfirm: boolean;
    apiActionDialogOpen: boolean;
    registrationQuestionsOpen: boolean;
    autoTranslateDialogOpen: boolean;
    hasLoggedInUser: boolean;
    haveLoadedDelayed: boolean;
    gotRatingsDialog: boolean;
    gotMediaRecorder: boolean;
    loadingStartedLoggedIn: boolean;
    haveLoadedDataViz: boolean;
    waitForUpgradeCounter: number;
    facebookPixelTrackingId: string | undefined;
    static get styles(): any[];
    renderSelectedDialog(): {} | TemplateResult<any>;
    render(): TemplateResult<1>;
    constructor();
    connectedCallback(): void;
    openPixelCookieConfirm(facebookPixelTrackingId: string): Promise<void>;
    _disableFaceookPixelTracking(): void;
    _agreeToFacebookPixelTracking(): void;
    _loggedInUser(event: CustomEvent): void;
    closeDialog(idName: string): void;
    dialogClosed(event: CustomEvent): void;
    _closeActionDialog(): void;
    _closeRegistrationQuestionsDialog(): void;
    loadDataViz(): void;
    openLoadingDialog(): Promise<void>;
    closeLoadingDialog(): Promise<void>;
    getRatingsDialogAsync(callback: Function): Promise<void>;
    getMediaRecorderAsync(callback: Function): void;
    getDialogAsync(idName: string, callback: Function): Promise<void>;
    _forgotPassword(): void;
}
//# sourceMappingURL=yp-app-dialogs.d.ts.map