import { PropertyValueMap, nothing } from "lit";
import { YpBaseElement } from "../common/yp-base-element.js";
import "@material/web/iconbutton/icon-button.js";
import "@material/web/iconbutton/icon-button.js";
export declare class YpSimpleHtmlEditor extends YpBaseElement {
    question: YpStructuredQuestionData;
    index: number | undefined;
    useSmallFont: boolean;
    value: string;
    characterCount: number;
    hasFocus: boolean;
    allowFirefoxFocusHack: boolean;
    showErrorLine: boolean;
    selectedImage: HTMLImageElement | undefined;
    static get styles(): any[];
    _onWidthInput(event: CustomEvent): void;
    _onHeightInput(event: CustomEvent): void;
    _onMarginInput(event: CustomEvent): void;
    closeImageDialog(): void;
    applyImageSize(): void;
    selectImage(image: HTMLImageElement): void;
    renderImageEditDialog(): import("lit-html").TemplateResult<1> | typeof nothing;
    render(): import("lit-html").TemplateResult<1>;
    deselectImage(): void;
    _setFocus(): void;
    connectedCallback(): void;
    update(changedProperties: PropertyValueMap<any> | Map<PropertyKey, unknown>): void;
    protected firstUpdated(_changedProperties: PropertyValueMap<any> | Map<PropertyKey, unknown>): void;
    _setBlur(event: CustomEvent): void;
    setRichValue(value: string): void;
    _updateCharacterCounter(): void;
    _keydown(event: KeyboardEvent): void;
    _paste(event: ClipboardEvent | CustomEvent): void;
    _changed(): void;
    validate(): boolean;
    _isSafariOrIe11(): boolean;
    _isFirefox(): boolean;
    _clearFormat(): void;
    _clearFormatM(): void;
    _toggleH1(): void;
    _toggleH1M(): void;
    _toggleH2(): void;
    _toggleH2M(): void;
    _toggleH3(): void;
    _toggleH3M(): void;
    _toggleH4(): void;
    _toggleH4M(): void;
    _toggleH5(): void;
    _toggleH5M(): void;
    _toggleH6(): void;
    _toggleH6M(): void;
    _toggleP(): void;
    _togglePM(): void;
    _toggleAlignLeft(): void;
    _toggleAlignLeftM(): void;
    _toggleAlignRight(): void;
    _toggleAlignRightM(): void;
    _toggleAlignCenter(): void;
    _toggleAlignCenterM(): void;
    _toggleAlignJustify(): void;
    _toggleAlignJustifyM(): void;
    _toggleBold(): void;
    _toggleBoldM(): void;
    _toggleItalic(): void;
    _toggleItalicM(): void;
    _toggleUnderline(): void;
    _toggleUnderlineM(): void;
    _toggleListBullets(): void;
    _toggleListBulletsM(): void;
    _toggleListNumbers(): void;
    _toggleListNumbersM(): void;
    _masterCommand(commandName: string, showDefaultUI?: boolean, value?: string): void;
}
//# sourceMappingURL=yp-simple-html-editor.d.ts.map