import { TemplateResult } from "lit";
import { YpBaseElement } from "../../common/yp-base-element.js";
export declare class YpAgentRunWidget extends YpBaseElement {
    agentProductId: number;
    runId: number;
    agentId: number;
    wsClientId: string;
    workflowGroupId: number;
    agentName: string;
    agentDescription: string;
    agentImageUrl: string;
    runStatus: YpAgentProductRunStatus;
    private agentState;
    private latestMessage;
    private progress;
    private statusInterval;
    workflow: string;
    maxRunsPerCycle: number;
    private api;
    constructor();
    connectedCallback(): void;
    updateWorkflow(updatedWorkflow: {
        workflow: YpWorkflowConfiguration;
        status: YpAgentProductRunStatus;
    }): void;
    get parsedWorkflow(): YpWorkflowConfiguration;
    disconnectedCallback(): void;
    private startStatusUpdates;
    private stopStatusUpdates;
    get latestMessageMarkdown(): string;
    private updateAgentStatus;
    static get styles(): any[];
    private getStepClass;
    private renderStep;
    private renderIcon;
    private renderAgentHeader;
    get shouldDisableStopButton(): boolean;
    get shouldDisableStartButton(): boolean;
    get isRunning(): boolean;
    get isWaitingOnUser(): boolean;
    get isCompleted(): boolean;
    private renderAgentRunningStatus;
    renderStartStopButtons(): TemplateResult<1>;
    get groupId(): number | undefined;
    private viewList;
    renderCompleted(): TemplateResult;
    renderWaitingOnUser(): TemplateResult<1>;
    render(): TemplateResult<1>;
}
//# sourceMappingURL=yp-agent-run-widget.d.ts.map