version: '3.9'

x-ai-assistant-common: &ai-assistant-common
  env_file: .env
  restart: always
  build:
    context: ../../.
    dockerfile: api/docker/ai-assistant/Dockerfile
  image: ai-assistant:current
  volumes:
    - client-app-dist:/usr/src/apps/ai-assistant/dist
  command: node ts-out/api/server.js
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9080/api/project/healthcheck"]
    interval: 30s
    timeout: 20s
    retries: 3
  network_mode: host
  logging:
    driver: "json-file"
    options:
      max-file: "2000"
      max-size: "25m"

services:
  redis_db:
    image: redis:6.2.13-alpine
    restart: always
    ports:
      - '6379:6379'
    network_mode: host
    volumes:
      - redis-db-data:/data

  webserver:
    container_name: webserver
    restart: always
    env_file: .env
    build:
      context: ./webserver/
      dockerfile: Dockerfile
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - webserver:/home
      - client-app-dist:/usr/src/apps/ai-assistant/dist
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${FULL_HOSTNAME}/api/project/healthcheck"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "2000"
        max-size: "25m"

  ai-assistant-1:
    <<: *ai-assistant-common
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/api/project/healthcheck"]
    environment:
      - PORT=9080

volumes:
  webserver:
  client-app-dist:
  redis-db-data:
    driver: local
