import { TemplateResult, nothing } from 'lit';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/progress/circular-progress.js';
import '@material/web/iconbutton/outlined-icon-button.js';
import '@material/web/icon/icon.js';
import '../yp-file-upload/yp-file-upload.js';
import '../common/yp-emoji-selector.js';
import '../yp-magic-text/yp-magic-text.js';
import './yp-point-actions.js';
import { YpBaseElement } from '../common/yp-base-element.js';
export declare class YpPoint extends YpBaseElement {
    point: YpPointData;
    post: YpPostData;
    group: YpGroupData;
    user: YpUserData | undefined;
    linkPoint: boolean;
    openTranscript: boolean;
    hideUser: boolean;
    hideActions: boolean;
    isEditing: boolean;
    isAdminCommentEditing: boolean;
    hasAdminComments: boolean;
    maxNumberOfPointsBeforeEditFrozen: number;
    editText: string | undefined;
    editAdminCommentText: string | undefined;
    videoActive: boolean;
    pointVideoPath: string | undefined;
    pointImageVideoPath: string | undefined;
    pointVideoId: number | undefined;
    audioActive: boolean;
    pointAudioPath: string | undefined;
    pointAudioId: number | undefined;
    checkingTranscript: boolean;
    portraitVideo: boolean;
    checkTranscriptError: boolean;
    playStartedAt: Date | undefined;
    videoPlayListener: Function | undefined;
    videoPauseListener: Function | undefined;
    videoEndedListener: Function | undefined;
    audioPlayListener: Function | undefined;
    audioPauseListener: Function | undefined;
    audioEndedListener: Function | undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    static get styles(): any[];
    renderAdminComments(): void;
    renderUserHeader(): typeof nothing | TemplateResult<1>;
    renderTextPoint(): TemplateResult<1>;
    renderVideoOrAudio(): TemplateResult<1>;
    renderEditPoint(): TemplateResult<1>;
    renderEditMenu(): TemplateResult<1>;
    render(): TemplateResult<1>;
    _setOpen(): void;
    _setClosed(): void;
    get isEditingSomething(): boolean;
    get showAdminComments(): boolean;
    get hasAdminCommentAccess(): boolean;
    get videoOrAudioActive(): boolean;
    _isEditingChanged(): void;
    _isAdminCommentEditingChanged(): void;
    _shareTap(event: CustomEvent): void;
    get pointUrl(): string;
    _linkIfNeeded(): void;
    _updateEmojiBindings(): void;
    _cancelEdit(): void;
    _saveEdit(): Promise<void>;
    _cancelAdminCommentEdit(): void;
    _saveAdminCommentEdit(): Promise<void>;
    _deletePoint(): void;
    _reallyDeletePoint(): Promise<void>;
    _reportPoint(): void;
    _onReport(): void;
    _editPoint(): void;
    _editAdminComment(): void;
    get hasPointAccess(): boolean;
    get canEditPoint(): boolean | null | undefined;
    firstUpdated(changedProperties: Map<string | number | symbol, unknown>): void;
    _pauseMediaPlayback(): void;
    _pointChanged(): void;
    _checkTranscriptStatus(): Promise<void>;
    _resetMedia(): void;
    loginName(): string | undefined;
    get isUpVote(): boolean;
    get isDownVote(): boolean;
}
//# sourceMappingURL=yp-point.d.ts.map