version: '3.9'

x-your-priorities-app-common: &your-priorities-app-common
  #  build: ./your-priorities-app/
  build:
    context: ../../.
    dockerfile: deployment/2024/your-priorities-app/Dockerfile
  env_file: .env
  environment:
   # - FORCE_DB_SYNC=true
  restart: always
  image: your-priorities-app:current
  command: node dist/server.js
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9080/api/users/has/AutoTranslation"]
    interval: 30s
    timeout: 20s
    retries: 3
  network_mode: host
  logging:
    driver: "json-file"
    options:
      max-file: "7"
      max-size: "1g"

x-your-priorities-worker-common: &your-priorities-worker-common
  #build: ./your-priorities-worker/
  build:
    context: ../../.
    dockerfile: deployment/2024/your-priorities-worker/Dockerfile
  restart: always
  env_file: .env
  command: node dist/services/workers/main.cjs
  network_mode: host
  logging:
    driver: "json-file"
    options:
      max-file: "7"
      max-size: "1g"

services:
  webserver:
    container_name: webserver
    restart: always
    env_file: .env
    build:
      context: ./webserver_reverse_proxy/
      dockerfile: Dockerfile
      args:
        - CERTBOT_CERT_FOLDER=${CERTBOT_CERT_FOLDER}
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - ./webserver_reverse_proxy/templates:/etc/nginx/templates
      - ./static_website:/static_website
      - geoip_data:/etc/nginx/geoip:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${FULL_HOSTNAME}/api/users/has/AutoTranslation"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1g"
    depends_on:
      - geoipupdate

  geoipupdate:
    image: maxmindinc/geoipupdate
    env_file: .env
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
    volumes:
      - geoip_data:/usr/share/GeoIP

  your-priorities-app1:
    <<: *your-priorities-app-common
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/api/users/has/AutoTranslation"]
    environment:
      - PORT=9080

  your-priorities-worker-1:
    <<: *your-priorities-worker-common

  your-priorities-worker-2:
    <<: *your-priorities-worker-common

volumes:
  geoip_data:
