import { YpBaseElement } from '../common/yp-base-element.js';
import '../common/yp-image.js';
export declare class YpPostCoverMedia extends YpBaseElement {
    post: YpPostData;
    topRadius: boolean;
    topLeftRadius: boolean;
    altTag: string | undefined;
    postAudioId: number | undefined;
    postVideoId: number | undefined;
    headerMode: boolean;
    disableMaps: boolean;
    mapActivated: boolean;
    streetViewActivated: boolean;
    tiny: boolean;
    staticMapsApiKey: string;
    uploadedDefaultPostImageId: number | undefined;
    defaultImageGroupId: number | undefined;
    defaultPostImageEnabled: boolean;
    showVideo: boolean;
    showAudio: boolean;
    portraitVideo: boolean;
    playStartedAt: Date | undefined;
    videoPlayListener: Function | undefined;
    videoPauseListener: Function | undefined;
    videoEndedListener: Function | undefined;
    audioPlayListener: Function | undefined;
    audioPauseListener: Function | undefined;
    audioEndedListener: Function | undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    static get styles(): any[];
    render(): import("lit-html").TemplateResult<1>;
    get sizingMode(): "contain" | "cover";
    get activeDefaultImageUrl(): string | undefined;
    _goToPost(): void;
    get latitude(): number;
    get longitude(): number;
    get isNoneActive(): boolean;
    get isCategoryActive(): boolean;
    _isDomainWithOldCategories(): boolean;
    get isCategoryLargeActive(): boolean;
    get isImageActive(): boolean;
    get isVideoActive(): boolean;
    get isAudioActive(): boolean;
    get isMapActive(): boolean;
    get isStreetViewActive(): boolean;
    get zoomLevel(): number | "10";
    get mapType(): string;
    _withCoverMediaType(post: YpPostData, mediaType: string): boolean;
    get mapPosition(): {
        lat: number;
        lng: number;
    };
    get postImagePath(): any;
    get postVideoPath(): string | undefined;
    get postAudioPath(): string | undefined;
    get postVideoPosterPath(): any;
    get categoryImagePath(): any;
}
//# sourceMappingURL=yp-post-cover-media.d.ts.map