import { nothing } from "lit";
import "@material/web/labs/navigationbar/navigation-bar.js";
import "@material/web/labs/navigationtab/navigation-tab.js";
import "@material/web/iconbutton/filled-icon-button.js";
import "@material/web/labs/navigationdrawer/navigation-drawer.js";
import "@material/web/list/list-item.js";
import "@material/web/list/list.js";
import "@material/web/iconbutton/outlined-icon-button.js";
import "@material/web/iconbutton/icon-button.js";
import "@material/mwc-snackbar";
import "@material/web/menu/menu.js";
import "./yp-analytics/yp-promotion-dashboard.js";
import "./yp-promotion/yp-campaign-manager.js";
import "../common/yp-image.js";
import { YpBaseElementWithLogin } from "../common/yp-base-element-with-login.js";
export declare class YpPromotionApp extends YpBaseElementWithLogin {
    collectionType: string;
    collectionId: number | string;
    collectionAction: string;
    page: string | undefined;
    pageIndex: number;
    collection: YpCollectionData | undefined;
    currentError: string | undefined;
    adminConfirmed: boolean;
    haveCheckedAdminRights: boolean;
    haveCheckedPromoterRights: boolean;
    active: boolean;
    lastSnackbarText: string | undefined;
    useCommunityId: string | number | undefined;
    originalCollectionType: string | undefined;
    collectionURL: string | undefined;
    static get styles(): any[];
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    _getCollection(): Promise<void>;
    renderTopBar(): import("lit-html").TemplateResult<1>;
    snackbarclosed(): void;
    render(): import("lit-html").TemplateResult<1>;
    renderNavigationBar(): import("lit-html").TemplateResult<1>;
    tabChanged(event: CustomEvent): void;
    exitToMainApp(): void;
    _setupEventListeners(): void;
    _removeEventListeners(): void;
    _gotAdminRights(event: CustomEvent): void;
    _gotPromoterRights(event: CustomEvent): void;
    _setAdminConfirmed(): void;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    _appError(event: CustomEvent): void;
    _renderPage(): typeof nothing | import("lit-html").TemplateResult<1>;
    _settingsColorChanged(event: CustomEvent): void;
}
//# sourceMappingURL=yp-promotion-app.d.ts.map