import { YpBaseElementWithLogin } from "../../common/yp-base-element-with-login";
import "@material/web/fab/fab.js";
import "@material/web/radio/radio.js";
import "@material/web/button/elevated-button.js";
import "@material/web/button/text-button.js";
import "@material/web/button/outlined-button.js";
import "@material/web/button/filled-button.js";
import "@material/web/checkbox/checkbox.js";
import "@material/web/iconbutton/icon-button.js";
import "../../common/yp-image.js";
import { YpCampaignApi } from "./YpCampaignApi";
export declare class YpCampaign extends YpBaseElementWithLogin {
    collectionType: string;
    collectionId: number;
    collection: YpCollectionData | undefined;
    campaign: YpCampaignData;
    campaignApi: YpCampaignApi;
    mediumToActivate: YpCampaignMediumData | undefined;
    mediumToShow: YpCampaignMediumData | undefined;
    confirmedActive: boolean;
    haveCopied: boolean;
    deleteCampaign(): Promise<void>;
    static get styles(): any[];
    get configuration(): YpCampaignConfigurationData;
    getMediumImageUrl(medium: string): "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/facebook.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/adwords.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/snapchat.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/instagram.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/twitter.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/youtube.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/linkedin.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/email.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/tiktok.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/whatsapp.png" | "https://yrpri-eu-direct-assets.s3.eu-west-1.amazonaws.com/SocialMediaImages/other.png";
    activate(medium: YpCampaignMediumData): Promise<void>;
    showMedium(medium: YpCampaignMediumData): Promise<void>;
    cancelActivation(): void;
    reallyActivate(): void;
    activeCheckboxChanged(event: CustomEvent): void;
    copyCurrentTextWithLink(medium: YpCampaignMediumData): void;
    copyCurrentText(medium: YpCampaignMediumData): void;
    copyCurrentLink(medium: YpCampaignMediumData): void;
    closeShowMedium(): void;
    renderTextWithLink(medium: YpCampaignMediumData): import("lit-html").TemplateResult<1>;
    renderActivateDialog(): import("lit-html").TemplateResult<1>;
    renderShowDialog(): import("lit-html").TemplateResult<1>;
    renderMedium(medium: YpCampaignMediumData): import("lit-html").TemplateResult<1>;
    render(): import("lit-html").TemplateResult<1>;
}
//# sourceMappingURL=yp-campaign.d.ts.map